/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contatos/detalhes` | `/contatos/detalhes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contatos` | `/contatos`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contatos/detalhes` | `/contatos/detalhes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contatos` | `/contatos`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mapa${`?${string}` | `#${string}` | ''}` | `/mapa${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cadastro${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contatos/detalhes${`?${string}` | `#${string}` | ''}` | `/contatos/detalhes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contatos${`?${string}` | `#${string}` | ''}` | `/contatos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contatos/detalhes` | `/contatos/detalhes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contatos` | `/contatos`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
